Fix formatting and spacing in main.yml

diff --git a/main.yml b/main.yml
--- a/main.yml
+++ b/main.yml
@@ -10,4 +10,4 @@ jobs:
         - run: echo "This woorkflow runs  successfully for this  particular action"
 
         -name: Simulating error 
-        run:   echo "Error taking place" ; exit 1
+        run: echo "Error taking place"; exit 1
